# Generated by Django 2.2.6 on 2020-01-08 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_shift'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slingshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=20)),
                ('ammo', models.CharField(choices=[('T', 'Tracer Rounds'), ('HS', 'Hog Scatter Shot'), ('BP', 'Bristle Piercing Rounds')], default='T', max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='shift',
            name='date',
            field=models.DateField(verbose_name='shift date'),
        ),
        migrations.AddField(
            model_name='chimp',
            name='slingshots',
            field=models.ManyToManyField(to='main_app.Slingshot'),
        ),
    ]
